In [ ]:
!sh get_datasets.sh

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])

In [9]:
np.dot(x.reshape(-1, 1), x.reshape(-1, 1))

ValueError: shapes (4,1) and (4,1) not aligned: 1 (dim 1) != 4 (dim 0)

In [8]:
x.reshape(-1, 1).shape

(4, 1)

In [28]:
x.shape

(4,)

In [29]:
y.shape

(2, 4)

In [12]:
y = np.array([[1,2,3,4], [5,6,7,8]])

In [32]:
np.dot(x, y.T)

array([30, 70])

In [22]:
!python word2vec.py

==== Gradient check for skip-gram with naiveSoftmaxLossAndGradient ====
Gradient check passed!
==== Gradient check for skip-gram with negSamplingLossAndGradient ====
Gradient check passed!

=== Results ===
Skip-Gram with naiveSoftmaxLossAndGradient
Your Result:
Loss: 11.16610900153398
Gradient wrt Center Vectors (dJ/dV):
 [[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [-1.26947339 -1.36873189  2.45158957]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
Gradient wrt Outside Vectors (dJ/dU):
 [[-0.41045956  0.18834851  1.43272264]
 [ 0.38202831 -0.17530219 -1.33348241]
 [ 0.07009355 -0.03216399 -0.24466386]
 [ 0.09472154 -0.04346509 -0.33062865]
 [-0.13638384  0.06258276  0.47605228]]

Expected Result: Value should approximate these:
Loss: 11.16610900153398
Gradient wrt Center Vectors (dJ/dV):
 [[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [-1.26947339 -1.36873189  2.45158957]
 [ 0.          0

In [23]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [33]:
a = np.array([1, 0, 3])

In [34]:
b = np.zeros((10, ))

In [35]:
b[a] = 1

In [51]:
ind

array([1, 0, 1])

In [38]:
y = np.array([[1,2,3,4], [5,6,7,8], [3,5,7,9]])

In [39]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 5, 7, 9]])

In [40]:
ind = np.array([1,0,1])

In [58]:
onehot = np.zeros((3, 4))

In [60]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.diagflat([1,0,1])

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

In [65]:
sum(y)

array([ 9, 13, 17, 21])

In [63]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 5, 7, 9]])